name: ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: install m68k-xelf
      run: |
        curl -OL https://github.com/yunkya2/elf2x68k/releases/download/20240929/elf2x68k-Linux-20240929.tar.bz2
        tar -jxf elf2x68k-Linux-20240929.tar.bz2
        extracted_dir=$(find . -maxdepth 1 -type d ! -name ".*" | head -n 1)
        echo "EXTRACTED_DIR=$PWD/$extracted_dir" >> $GITHUB_ENV
        echo "$PWD/$extracted_dir/bin" >> $GITHUB_PATH
        chmod +x $PWD/$extracted_dir/bin/*

    - name: make
      run: |
        m68k-xelf-gcc --version
        cd src
        make

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: src/*.x
